"""Add OAuth and profile customization fields

Revision ID: 036b0b01c878
Revises: 684056307bc7
Create Date: 2025-09-20 00:06:48.257275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036b0b01c878'
down_revision: Union[str, Sequence[str], None] = '684056307bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('discord_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('instagram_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('background_image', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('background_color', sa.String(length=7), nullable=True))
    op.add_column('users', sa.Column('favorite_song', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['github_id'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'favorite_song')
    op.drop_column('users', 'background_color')
    op.drop_column('users', 'background_image')
    op.drop_column('users', 'instagram_username')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'discord_username')
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
