"""add_stripe_subscription_id_field

Revision ID: 0eb442e82756
Revises: d5bed757fb5b
Create Date: 2025-09-20 18:45:16.824092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb442e82756'
down_revision: Union[str, Sequence[str], None] = 'd5bed757fb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_subscription_id')
    # ### end Alembic commands ###
