"""Add referral system fields

Revision ID: 50bf5a9d58c7
Revises: 9f59cdbb4f7f
Create Date: 2025-09-21 16:01:27.763140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bf5a9d58c7'
down_revision: Union[str, Sequence[str], None] = '9f59cdbb4f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
